routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');

Route::get('/password_change', 'ProfileController@changePassword')->name('password.change');

Route::post('/password_save', 'ProfileController@saveNewPassword')->name('password.save');

Route::get('/status/{msg}', 'ProfileController@status')->name('status');
Route::get('/passChanged', 'ProfileController@status')->name('status');

Route::resource('user', 'ProfileController')->except([
    'destroy', 'create', 'store',
])->middleware('verified');

Route::post('update_profile', 'ProfileController@updateProfile')->name('user.updated')->middleware('verified');

Route::get('{handle}', ['as' => 'handle', 'uses' => 'ProfileController@show']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;



class User extends Authenticatable implements MustVerifyEmail
{

    const PERSONAL_NAME = 1;
    const COMPANY_NAME = 2;

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'handle', 'email', 'password', 'profile_image', 'crypto_wallet_address', 'iban', 'public_nickname', 'company'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getImageAttribute()
    {
        return $this->profile_image;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('web');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Traits\UploadTrait;
use App\User;
use Illuminate\Foundation\Auth\ResetsPasswords;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    use UploadTrait;
    use ResetsPasswords;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }



    /**
     * Display the specified resource.
     *q
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    /**
     * Display the specified resource.
     *
     * @param $handle
     * @return void
     */
    public function show($handle)
    {
        $user = User::where('handle', $handle)->first();

        if($user) {
            return view('users.show_user', ['user' => $user]);
        }
        else {
            return view('users.show_user');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return view('profile', ['user' => Auth::user()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateProfile(Request $request)
    {
        // Get current user
        $user = User::findOrFail(auth()->user()->id);
        // Set user name
        $user->first_name = $request->input('first_name') ? $request->input('first_name') : '';
        $user->last_name = $request->input('last_name') ? $request->input('last_name') : '';
        $user->handle = $request->input('handle') ? $request->input('handle') : '';
        $user->email = $request->input('email') ? $request->input('email') : '';
        $user->crypto_wallet_address = $request->input('crypto_wallet_address') ? $request->input('crypto_wallet_address') : '';
        $user->iban = $request->input('iban') ? $request->input('iban') : '';
        $user->public_nickname = $request->input('publicName') ? $request->input('publicName') : '';
        $user->company = $request->input('company') ? $request->input('company') : '';

        // Check if a profile image has been uploaded
        if ($request->has('profile_image')) {
            // Get image file
            $image = $request->file('profile_image');
            // Make a image name based on user name and current timestamp
            $name = str_slug($request->input('name')).'_'.time();
            // Define folder path
            $folder = '/images/';
            // Make a file path where image will be stored [ folder path + file name + file extension]
            $filePath = $folder . $name. '.' . $image->getClientOriginalExtension();
            // Upload image
            $this->uploadOne($image, $folder, 'public', $name);
            // Set user profile image path in database to filePath
            $user->profile_image = $filePath;
        }
        // Persist user record to database
        $user->save();

        // Return user back and show a flash message
        return redirect()->back()->with(['status' => 'Profile updated successfully.']);
    }

    public function status($msg) {
        return view('status')->with('msg', $msg);
    }

    public function changePassword() {
        return view('change_pass')->with('usr', Auth::user()->id);
    }

    public function saveNewPassword(Request $request) {
        $user = User::find(Auth::user()->id);

        $newPassword = Hash::make($request->get('password'));

        $user->password = $newPassword;
        $user->save();

        $data['pass'] = true;
        $data['usr'] = Auth::user()->id;

        return view('passChange', $data);
    }
}

resources/views/change_pass.blade.php
@extends('layouts.emy')

@section('content')
    <div class="row">
        <div class="d-none d-md-flex col-md-6 left-signup">
            <a href="{{ route('home') }}"><img src="{{ asset('/media/logo/logo.svg') }}" alt="logo" /></a>
            <h1>Welcome to <br />Emyapp!</h1>
            <h2>A Twitter for payments.</h2>
        </div>


        <div class="col-12 col-md-6  offset-xl-1 col-xl-5 right-signup">
            <h2>Please enter your new <br> password</h2>
            <form method="POST" action="{{ route('password.save') }}">
                @csrf
                <div class="input-box">
                    <input id="password" type="password" placeholder="New Password" @error('password') class="is-invalid @enderror" name="password" value="{{ old('password') }}" required>
                    <i class="icon-password"></i>
                    <label class="floating-label">New Password</label>
                    @error('password')
                    <span class="validation-alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="input-box">
                    <input id="password-confirm" type="password" placeholder="Repeat Password" class="@error('password') is-invalid @enderror" name="password_confirmation" value="{{ old('password_confirmation') }}" required>
                    <i class="icon-password"></i>
                    <label class="floating-label">Repeat Password</label>
                </div>

                <p class="signup-terms">
                    <button type="submit" class="button-link">
                        {{ __('Save password') }}
                    </button>
                    <span>Do not want to change password?</span><br/>
                    <a href="{{ URL::previous()  }}"><u>Go back</u></a>
                </p>
            </form>

    </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    @if (session('verifySuccess'))
        <div class="alert alert-success" role="alert">
            Email verification successful!
        </div>
    @endif

    @if (session('linkExpired'))
        <div class="alert alert-success" role="alert">
            Link expired :(
        </div>
    @endif

    @if (session('alreadyVerified'))
        <div class="alert alert-success" role="alert">
            alreadyVerified
        </div>
    @endif

    @auth
        You are logged in!
    @endauth
@endsection

resources/views/layouts/emy.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Emy - Crypto for humans</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body class="white-stripes">
<div class="container signup-section">
    @yield('content')
</div>

<div class="bot-mask"></div>

<script src="{{ asset('js/bootstrap.min.js') }}" defer></script>
<script src="{{ asset('js/main.js') }}" defer></script>
<script src="{{ asset('js/signup.js') }}" defer></script>
</body>
</html>

resources/views/passChange.blade.php
@extends('layouts.emy')

@section('content')
    <div class="row">
        <div class="d-none d-md-flex col-md-6 left-signup">
            <a href="{{ route('home') }}"><img src="{{ asset('/media/logo/logo.svg') }}" alt="logo" /></a>
            <h1>Welcome to <br />Emyapp!</h1>
            <h2>A Twitter for payments.</h2>
        </div>

        @if(isset($usr))

            <div class="col-12 col-md-6  offset-xl-1 col-xl-5 right-signup">
                <img width="74" class="rounded-circle" height="75" src="{{ asset('/images/checkmark.svg') }}" alt="logo" />
                <a href="#"><h2>Your password has been <br> changed</h2></a>
                <a href="{{ route('user.edit', $usr) }}"><button class="button-link">
                        {{ __('Proceed to your account') }}
                    </button></a>
            </div>
        @endif
    </div>
@endsection

resources/views/profile.blade.php
@extends('layouts.emy')

@section('content')

    <div class="row">
        <div class="d-none d-md-flex col-md-6 left-signup">
            <a href="#"><img src="{{ asset('/media/logo/logo.svg') }}" alt="logo" /></a>
            <h1>Welcome to <br />Emyapp!</h1>
            <h2>A Twitter for payments.</h2>
        </div>
        <div class="col-12 col-md-6  offset-xl-1 col-xl-5 right-signup user-profile-edit">

            @if (auth()->user()->profile_image)
                <img width="74" class="rounded-circle" height="75" src="{{ auth()->user()->profile_image }}">
            @else
                <img width="74" class="rounded-circle" height="75" src="{{ asset('/images/profile_icon.svg') }}" alt="logo" />
            @endif

            <span class="user-name">Hello {{ $user->first_name }} {{ $user->last_name }}</span>
            <h2>We will let you know as soon as we launch the app</h2>
            <h2>Profile informations</h2>

                <form method="POST" enctype="multipart/form-data" action="{{ route('user.updated') }}">
                @csrf
                <div class="input-box">
                    <input id="first_name" type="text" placeholder="First Name" class="@error('first_name') is-invalid @enderror" name="first_name" value="{{ $user->first_name  }}" required>
                    <i class="icon-profile"></i>
                    <label class="floating-label">First Name</label>
                    @error('first_name')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="input-box">
                    <input id="last_name" type="text" placeholder="Last Name" class=" @error('last_name') is-invalid @enderror" name="last_name" value="{{ $user->last_name }}" required>
                    <i class="icon-profile"></i>
                    <label class="floating-label">Last Name</label>
                    @error('last_name')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="input-box">
                    <input id="email" type="email" placeholder="Email" class=" @error('email')is-invalid @enderror" name="email" value="{{ $user->email }}" required>
                    <i class="icon-email"></i>
                    <label class="floating-label">Email</label>
                    @error('email')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="input-box">
                    <input id="company" type="text" placeholder="Company name" class="@error('company') is-invalid @enderror" name="company" value="{{ $user->company  }}" required>
                    <i class="icon-profile"></i>
                    <label class="floating-label">Company name</label>
                    @error('company')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="input-box">
                    <input id="handle" type="text" placeholder="Handle" name="handle" value="{{ $user->handle  }}" required>
                    <i class="icon-handle"></i>
                    <label class="floating-label">Handle</label>
                    @error('handle')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="input-box" style="display: flex">
                    <label>Crypto wallet address</label>
                    <div class="radio">
                        <input id="radio-1" name="publicName" value="1" type="radio" {{ $user->public_nickname == 1 ? 'checked' : '' }}>
                        <label for="radio-1" class="radio-label">Personal Name</label>
                    </div>

                    <div class="radio">
                        <input id="radio-2" name="publicName" value="2" type="radio" {{ ($user->public_nickname == 2) ? 'checked' : '' }}>
                        <label  for="radio-2" class="radio-label">Company Name</label>
                    </div>
                    @error('publicName')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
                <div class="input-box">
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input id="profile_image" class="custom-file-input" type="file" name="profile_image">
                            <label class="custom-file-label" for="inputGroupFile01">Choose profile image</label>
                        </div>
                        @error('profile_image')
                        <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                        @enderror
                    </div>
                </div>
                <div class="input-box">
                    <input id="crypto_wallet_address" type="text" placeholder="Crypto wallet address" class=" @error('crypto_wallet_address') is-invalid @enderror" name="crypto_wallet_address" value="{{ $user->crypto_wallet_address }}" required>
                    <i class="icon-handle"></i>
                    <label class="floating-label">Crypto wallet address</label>
                    @error('crypto_wallet_address')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="input-box">
                    <input id="iban" type="text" placeholder="IBAN" class=" @error('iban') is-invalid @enderror" name="iban" value="{{ $user->iban }}" required>
                    <i class="icon-handle"></i>
                    <label class="floating-label">IBAN</label>
                    @error('iban')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                </div>


                <div class="input-box">
                    <input id="password" type="password" placeholder="Password" class=" @error('password') is-invalid @enderror" name="password" value="{{ $user->password }}" disabled>
                    <i class="icon-password"></i>
                    <label class="floating-label">Password</label>
                    @error('password')
                    <span class="validation-alert" role="alert">
                        {{ $message }}
                    </span>
                    @enderror
                    <a href="{{ route('password.change') }}"><u>Change password</u></a>
                </div>
                <p class="signup-terms">
                    By signing up you agree to our <br />
                    <a href="#">Terms & Conditions</a> and
                    <a href="#">Privacy policy</a>
                </p>
                <button type="submit">{{ __('Save') }}</button>
            </form>
        </div>
    </div>

@endsection

resources/views/status.blade.php
@extends('layouts.emy')

@section('content')
    <div class="row">
        <div class="d-none d-md-flex col-md-6 left-signup">
            <a href="{{ route('home') }}"><img src="{{ asset('/media/logo/logo.svg') }}" alt="logo" /></a>
            <h1>Welcome to <br />Emyapp!</h1>
            <h2>A Twitter for payments.</h2>
        </div>


        @if(isset($msg))

            <div class="col-12 col-md-6  offset-xl-1 col-xl-5 right-signup">
                <img width="74" class="rounded-circle" height="75" src="{{ asset('/images/checkmark.svg') }}" alt="logo" />
                <a href="#"><h2>Your password has been <br> changed</h2></a>
                <a href="{{ route('login') }}"><button class="button-link">
                        {{ __('Proceed to your account') }}
                    </button></a>
            </div>
        @endif
    </div>
@endsection

resources/views/users/show_user.blade.php
@extends('layouts.emy')

@section('content')
    <div class="row">
        <div class="d-none d-md-flex col-md-6 left-signup">
            <a href="{{ route('home') }}"><img src="{{ asset('/media/logo/logo.svg') }}" alt="logo" /></a>
            <h1>Welcome to <br />Emyapp!</h1>
            <h2>A Twitter for payments.</h2>
        </div>


        <div class="col-12 col-md-6  offset-xl-1 col-xl-5 right-signup">

            @if(!empty($user))
                    @if(!$user['profile_image'])
                        <img class="rounded-circle text-center" style="margin: 0 auto" width="175" height="175" align="center" src="{{ asset('images/default_user.png') }}"><br/>
                    @else

                        <img class="rounded-circle text-center" style="margin: 0 auto" width="175" height="175" align="center" src="{{ asset( $user['profile_image']) }}"><br/>
                    @endif
                        <h1>Profile</h1>
                        <p class="title">@handle: {{ $user['handle'] }}</p><br/>

                        @if($user['public_nickname'] == 1)
                            <p class="title">First name: {{ $user['first_name'] }}</p><br/>
                            <p class="title">Last name: {{ $user['last_name'] }}</p><br/>
                        @elseif($user['public_nickname'] == 2)
                            <p>Public name: {{ $user['company'] }}</p><br/>
                        @else
                            <p class="title">User still didn't select this option.</p><br/>
                        @endif

                        <p class="title">Crypto wallet address: {{ $user['crypto_wallet_address'] }}</p><br/>
                        <p class="title">IBAN: {{ $user['iban'] }}</p><br/>

                        @else
                            <img width="74" class="rounded-circle" height="75" src="{{ asset('/images/error.png') }}" alt="logo" />
                            <span class="user-name">Couldn't find user</span>
                            <h2>User with such @handle doesn't exist.</h2>
                        @endif

                </div>
    </div>

@endsection